#!/bin/sh
# postinst script for hudson
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    configure)

		/etc/init.d/tomcat6 stop
		
		# remove deployed webapp from tomcat, just to be sure
		if [ -d /var/lib/tomcat6/webapps/downloads ]; then
			rm -rf /var/lib/tomcat6/webapps/downloads
		fi
		
		
		/etc/init.d/tomcat6 start
		
	;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
		
esac




